### PR TITLE
Add Circle CI config for Nightly Builds

### PR DESCRIPTION
**Pull request by loicteixeira**
Following the procedure for [Nightly testing of official plugins](https://github.com/wagtail/wagtail/wiki/Nightly-testing-of-official-plugins).

@kaedroho, I do not seem to have the rights to configure the project on Circle CI. Can you set `SLACK_WEBHOOK_URL` for `wagtail-bakery` for me? After that, we should be able to merge this PR.

### CODE REVIEW

**Comment by loicteixeira** [comment]
Rebased on master with the fix to factory-boy which was causing the CI to fail.

**Comment by kaedroho** [comment]
All configured now, thanks!

**Review by kaedroho — APPROVED** [review]

**Comment by loicteixeira** [comment]
Awesome, thanks. Let's see if it runs tonight 🕛

**Comment by loicteixeira** [comment]
Err I'm stupid, I didn't change the test command in the workflow.. I'll get onto that.

**Pull request merged**
