### PR TITLE
Adding a SitemapBuildableView to generate a wagtail sitemap.

### LINKED ISSUE #37: Add SitemapBuildableView
Sites need a sitemap and it'd be great to be able to generate this as part of the static build process.

I'm currently putting up a PR to answer this issue.

### PR DESCRIPTION
**Pull request by NDevox**
This will fix #37.

### CODE REVIEW

**Comment by loicteixeira** [comment]
Hi @NDevox, thank you for your contribution and sorry for the late review.

Unfortunately with Wagtail before 2.2, it fails with the following error `AttributeError: 'WSGIRequest' object has no attribute 'site'`. Indeed, as you can see here it tries to [query the request's site](https://github.com/wagtail/wagtail/blob/5728de51eff62518d211e3f8309b1bf3a692f24d/wagtail/contrib/wagtailsitemaps/views.py#L17) in the view but this behaviour was changed in wagtail/wagtail@a3fe8eb3b1141e50457d72516f9bd5d45b07cc6e which is included in Wagtail 2.2. It might simply be a matter of duplicating the [new get_wagtail_site](https://github.com/wagtail/wagtail/blob/a3fe8eb3b1141e50457d72516f9bd5d45b07cc6e/wagtail/contrib/sitemaps/sitemap_generator.py#L23-L29) for versions prior to 2.2. However we might not need to do so as we might drop compatibility with Wagtail prior to 2.2 soon (see #36).

In addition, I haven't ran test for it yet but I suspect it won't be compatible with the multi-site option. As you can see, other views' build path differs whether we use multi sites:

https://github.com/wagtail/wagtail-bakery/blob/0937dde07d1791a3780079a1b6959eb0b9c43d55/src/wagtailbakery/views.py#L65-L69

**Comment by Benoss** [comment]
I am using part of your pull request as my own SitemapBuildableView works perfectly for my use case. Would be good to get this work with multisite and merged at some point knowing that the current LTS is 2.3 Dropping support for < 2.3 would make sense

**Comment by loicteixeira** [comment]
I'm focussing on preparing the Wagtail repository for Hacktoberfest over the next couple weeks, then I'll work towards merging this and fixing other issues which have been reported.

**Comment by NDevox** [comment]
@loicteixeira Sorry I dropped off on this one!

If we drop support for < 2.3 obviously that makes things simpler. I'll wait for your input on that one.

I've not tested for multisite, I've also not had to use it for wagtail before! I can give that an attempt and see what happens. My thought on this one would be what behaviour would be expected? A class that builds all sitemaps in one go? Would we want to allow sites to be filtered? or demand a specific class instance for each site?

**Comment by loicteixeira** [comment]
I'll update the test matrix as per #36 this week so you should be able to rebase on that after.

As for the expected behaviour, yes, one class which builds all sitemaps in one go, as does the base view:

https://github.com/wagtail/wagtail-bakery/blob/0937dde07d1791a3780079a1b6959eb0b9c43d55/src/wagtailbakery/views.py#L65-L69

**Comment by loicteixeira** [comment]
@NDevox I rebased & continued your work on the PR linked above which supersed this one. Thank you for getting this started.

**Pull request closed without merging**
